services:
  php:
    build:
      context: .
    container_name: symfony-php
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      SYMFONY_ENV: dev
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets:/etc/nginx/snippets
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
